global:
  scrape_interval:     10s # Как часто собирать метрики
  evaluation_interval: 2s # Как часто вычислять правила агрегации и алертинга


rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "app"
    metrics_path: '/metrics'
    static_configs:
      - targets: [ "localhost:2112" ]
